"""
Writing the manuscript out as markdown into a git repo.

Every compile is a commit. That is the whole versioning story: `git diff` after
a recompile shows exactly what the model changed, and `git revert` undoes it.
For that to mean anything the write has to be deterministic, which is why
render.py caches -- an unchanged paragraph must produce a byte-identical file
or every compile would look like a rewrite.

The manuscript directory is disposable. It is regenerated from the store, so
deleting it loses nothing.
"""

from __future__ import annotations

import pathlib
import re
import subprocess

import ground as G


def slug(title: str) -> str:
    # En-dash first: chapter titles are year ranges like "1953-1986", and
    # stripping it silently welds them into "19531986".
    s = title.lower().replace("\u2013", "-").replace("\u2014", "-")
    s = re.sub(r"[^\w\s-]", "", s).strip()
    return re.sub(r"[-\s]+", "-", s) or "chapter"


def _git(repo: pathlib.Path, *args: str, check: bool = True):
    return subprocess.run(["git", "-C", str(repo), *args],
                          capture_output=True, text=True, check=check)


def ensure_repo(path: str | pathlib.Path) -> pathlib.Path:
    repo = pathlib.Path(path)
    repo.mkdir(parents=True, exist_ok=True)
    if not (repo / ".git").exists():
        _git(repo, "init", "-q")
        # Local identity only; never touches the user's global git config.
        _git(repo, "config", "user.name", "sargam")
        _git(repo, "config", "user.email", "sargam@localhost")
    return repo


def write(store, book: dict, out_dir: str | pathlib.Path,
          strip: bool = True) -> dict:
    """Render the compiled book to markdown files. Returns a write report."""
    repo = ensure_repo(out_dir)
    for old in repo.glob("*.md"):
        old.unlink()

    dropped_total = 0
    manifest = []
    for i, chap in enumerate(book["chapters"], 1):
        lines = [f"# {chap['title']}", ""]
        for para in chap["paragraphs"]:
            body = para["body"]
            if strip:
                vs = G.from_rows(store.groundings(para["id"]))
                body, dropped = G.strip_unsupported(body, vs)
                dropped_total += dropped
            if not body.strip():
                continue
            lines.append(body.strip())
            if para.get("flagged"):
                lines.append("")
                lines.append("> [!review] Sources changed under a frozen "
                             "paragraph. Left as written.")
            lines.append("")
        name = f"{i:02d}-{slug(chap['title'])}.md"
        (repo / name).write_text("\n".join(lines).rstrip() + "\n")
        manifest.append(name)

    idx = ["# Manuscript", ""]
    for i, (chap, name) in enumerate(zip(book["chapters"], manifest), 1):
        idx.append(f"{i}. [{chap['title']}]({name}) "
                   f"— {len(chap['paragraphs'])} paragraphs, "
                   f"{len(chap['events'])} events")
    idx.append("")
    idx.append("Generated by sargam. Do not edit these files: they are "
               "recompiled from the event store and your edits would be "
               "overwritten. Change the source material instead.")
    (repo / "README.md").write_text("\n".join(idx) + "\n")

    return {"repo": repo, "files": manifest, "dropped": dropped_total}


def commit(repo: pathlib.Path, message: str) -> str | None:
    """Commit the manuscript. Returns the sha, or None when nothing changed --
    which is the good case: it means the recompile was a no-op."""
    _git(repo, "add", "-A")
    st = _git(repo, "status", "--porcelain")
    if not st.stdout.strip():
        return None
    _git(repo, "commit", "-q", "-m", message)
    return _git(repo, "rev-parse", "--short", "HEAD").stdout.strip()


def diffstat(repo: pathlib.Path) -> str:
    r = _git(repo, "diff", "--stat", "HEAD~1", "HEAD", check=False)
    return r.stdout.strip() if r.returncode == 0 else ""
